export default {
  login: "vivekpandey76",
  id: 74551457,
  node_id: "MDQ6VXNlcjc0NTUxNDU3",
  avatar_url: "https://avatars.githubusercontent.com/u/74551457?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/vivekpandey76",
  html_url: "https://github.com/vivekpandey76",
  followers_url: "https://api.github.com/users/vivekpandey76/followers",
  following_url:
    "https://api.github.com/users/vivekpandey76/following{/other_user}",
  gists_url: "https://api.github.com/users/vivekpandey76/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/vivekpandey76/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/vivekpandey76/subscriptions",
  organizations_url: "https://api.github.com/users/vivekpandey76/orgs",
  repos_url: "https://api.github.com/users/vivekpandey76/repos",
  events_url: "https://api.github.com/users/vivekpandey76/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/vivekpandey76/received_events",
  type: "User",
  site_admin: false,
  name: "Vivek pandey",
  company: "me",
  blog: "",
  location: "Virar ",
  email: null,
  hireable: null,
  bio: "I'm a student,Front End +Back End developer,and learner!",
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 2,
  following: 4,
  created_at: "2020-11-16T14:43:21Z",
  updated_at: "2021-05-28T13:27:32Z",
};
